plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

repositories {
    mavenLocal()
    maven {
        url = 'https://maven.blamejared.com'
    }
    maven {
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchmentVersion}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation project(":common")

    modImplementation('com.epherical.epherolib:EpheroLib-fabric:1.2.0-1.20.1')
    modImplementation "vazkii.patchouli:Patchouli:1.20.1-84-FABRIC-SNAPSHOT"

    modCompileOnly "com.terraformersmc:modmenu:${rootProject.modmenu_version}",{
        exclude(group: "net.fabricmc.fabric-api")
    }
}

loom {
    accessWidenerPath.set(file("src/main/resources/croptopia.accesswidener"))
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

import org.gradle.api.file.RelativePath

tasks.named('processResources', ProcessResources) {
    includeEmptyDirs = false

    filesMatching(['**/data/**', '**/dependents/**']) {
        expand dependent: 'c'
    }

    eachFile { details ->
        def segments = details.relativePath.segments as List

        for (int i = 0; i < segments.size() - 1; i++) {
            if (segments[i] == 'dependents' && segments[i + 1] == 'platform') {
                def rewritten = []
                rewritten.addAll(segments.subList(0, i))
                rewritten.add('data')
                rewritten.add('c')
                if (i + 2 < segments.size()) {
                    rewritten.addAll(segments.subList(i + 2, segments.size()))
                }

                details.relativePath = new RelativePath(details.relativePath.isFile(), *rewritten)
                break
            }
        }
    }
}
