plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT' apply(false)
    id 'net.neoforged.moddev.legacyforge' version '2.0.141' apply(false)
}


tasks.register('buildAllLoaders') {
    group = 'build'
    description = 'Builds both Fabric and Forge loader projects.'
    dependsOn ':fabric:build', ':forge:build'
}
