# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=4.2.4
group=com.epherical
java_version=21
# Common
minecraft_version=1.21.1
mod_name=Croptopia
mod_author=iThonk
mod_id=croptopia
license=MIT
credits=
description=Adding New Foods to the game!
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10
# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9
# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)
# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
