# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=4.3.2
group=com.epherical
java_version=25
# Common
minecraft_version=26.2
mod_name=Croptopia
mod_author=iThonk
mod_id=croptopia
license=MIT
credits=
description=Adding New Foods to the game!
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1


# Fabric
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
