plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

repositories {
    mavenLocal()
    maven {
        url = 'https://maven.blamejared.com'
    }
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    //config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchmentVersion
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    modImplementation ("vazkii.patchouli:Patchouli:1.20.1-85-FORGE")
    modImplementation ('com.epherical.epherolib:EpheroLib-forge:1.2.0-1.20.1')
}

import org.gradle.api.file.RelativePath

tasks.named('processResources', ProcessResources) {
    includeEmptyDirs = false

    filesMatching(['**/data/**', '**/dependents/**']) {
        expand dependent: 'forge'
    }

    eachFile { details ->
        def segments = details.relativePath.segments as List

        for (int i = 0; i < segments.size() - 1; i++) {
            if (segments[i] == 'dependents' && segments[i + 1] == 'platform') {
                def rewritten = []
                rewritten.addAll(segments.subList(0, i))
                rewritten.add('data')
                rewritten.add('forge')
                if (i + 2 < segments.size()) {
                    rewritten.addAll(segments.subList(i + 2, segments.size()))
                }

                details.relativePath = new RelativePath(details.relativePath.isFile(), *rewritten)
                break
            }
        }
    }
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.forge.mixins.json"
    ])
}
