plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}


repositories {
    mavenLocal()
    maven {
        url = 'https://maven.blamejared.com'
    }
}


dependencies {
    implementation ('com.epherical.epherolib:epherolib-neoforge-26.1:1.3.0')
    implementation ("vazkii.patchouli:patchouli-neoforge:26.1-94-SNAPSHOT")
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def commonProject = rootProject.project(':common')
    def at = commonProject.file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("runs/client"))
        }
        data {
            clientData()
            gameDirectory = this.mkdir(this.file("runs/data"))
            programArguments.addAll '--mod', project.mod_id, '--all',
                    '--output', commonProject.file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath(),
                    '--existing', commonProject.file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            this.file("runs/server").createParentDirectories()
            gameDirectory = this.mkdir(this.file("runs/server"))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}
