package me.thonk.croptopia.registry;

import me.thonk.common.ItemNames;
import me.thonk.croptopia.items.Drink;
import me.thonk.croptopia.items.GuideBookItem;
import me.thonk.croptopia.items.SeedItem;
import net.minecraft.item.*;
import net.minecraftforge.event.RegistryEvent;

import static me.thonk.croptopia.CroptopiaForge.*;
import static me.thonk.croptopia.registry.FoodRegistry.*;
import static net.minecraft.world.biome.Biome.Category.*;

public class ItemRegistry {
    // Fruits & Vegetables // cropitem
    public static Item artichoke;
    public static Item asparagus;
    public static Item barley;
    public static Item bellPepper;
    public static Item blackBean;
    public static Item blackberry;
    public static Item blueberry;
    public static Item broccoli;
    public static Item cabbage;
    public static Item cantaloupe;
    public static Item cauliflower;
    public static Item celery;
    public static Item coffeeBeans;
    public static Item corn;
    public static Item cranberry;
    public static Item cucumber;
    public static Item currant;
    public static Item eggplant;
    public static Item elderberry;
    public static Item garlic;
    public static Item grape;
    public static Item greenBean;
    public static Item greenOnion;
    public static Item honeydew;
    public static Item hops;
    public static Item kale;
    public static Item kiwi;
    public static Item leek;
    public static Item lettuce;
    public static Item oat;
    public static Item olive;
    public static Item onion;
    public static Item peanut;
    public static Item pineapple;
    public static Item radish;
    public static Item raspberry;
    public static Item rhubarb;
    public static Item rice;
    public static Item rutabaga;
    public static Item saguaro;
    public static Item soybean;
    public static Item spinach;
    public static Item squash;
    public static Item strawberry;
    public static Item sweetPotato;
    public static Item tomatillo;
    public static Item tomato;
    public static Item turnip;
    public static Item yam;
    public static Item zucchini;

    // Trees
    public static Item orange;
    public static Item banana;
    public static Item persimmon;
    public static Item plum;
    public static Item cherry;
    public static Item lemon;
    public static Item grapefruit;
    public static Item kumquat;
    public static Item peach;
    public static Item coconut;
    public static Item nutmeg;
    public static Item fig;
    public static Item nectarine;
    public static Item mango;
    public static Item dragonFruit;
    public static Item starFruit;
    public static Item avocado;
    public static Item apricot;
    public static Item pear;
    public static Item lime;
    public static Item date;
    public static Item almond;
    public static Item cashew;
    public static Item pecan;
    public static Item walnut;

    // Spices
    public static Item mustard;
    public static Item vanilla;
    public static Item paprika;
    public static Item chilePepper;
    public static Item salt;
    public static Item turmeric;
    public static Item ginger;
    // Herbs
    public static Item basil;


    public static Item artichokeSeed;
    public static Item asparagusSeed;
    public static Item bellPepperSeed;
    public static Item blackBeanSeed;
    public static Item blackberrySeed;
    public static Item blueberrySeed;
    public static Item broccoliSeed;
    public static Item cabbageSeed;
    public static Item cantaloupeSeed;
    public static Item cauliflowerSeed;
    public static Item celerySeed;
    public static Item coffeeSeed;
    public static Item cornSeed;
    public static Item cranberrySeed;
    public static Item cucumberSeed;
    public static Item currantSeed;
    public static Item eggplantSeed;
    public static Item elderberrySeed;
    public static Item garlicSeed;
    public static Item grapeSeed;
    public static Item greenBeanSeed;
    public static Item greenOnionSeed;
    public static Item honeydewSeed;
    public static Item hopsSeed;
    public static Item kaleSeed;
    public static Item kiwiSeed;
    public static Item leekSeed;
    public static Item lettuceSeed;
    public static Item oliveSeed;
    public static Item onionSeed;
    public static Item peanutSeed;
    public static Item pineappleSeed;
    public static Item radishSeed;
    public static Item raspberrySeed;
    public static Item rhubarbSeed;
    public static Item riceSeed;
    public static Item rutabagaSeed;
    public static Item saguaroSeed;
    public static Item spinachSeed;
    public static Item squashSeed;
    public static Item strawberrySeed;
    public static Item sweetPotatoSeed;
    public static Item tomatilloSeed;
    public static Item tomatoSeed;
    public static Item turnipSeed;
    public static Item yamSeed;
    public static Item zucchiniSeed;
    public static Item mustardSeed;
    public static Item pepperSeed;
    public static Item turmericSeed;
    public static Item gingerSeed;
    public static Item basilSeed;
    public static Item oatSeed;
    public static Item barleySeed;
    public static Item soybeanSeed;
    public static Item vanillaSeed;



    public static Item appleSapling;
    public static Item bananaSapling;
    public static Item orangeSapling;
    public static Item persimmonSapling;
    public static Item plumSapling;
    public static Item cherrySapling;
    public static Item lemonSapling;
    public static Item grapefruitSapling;
    public static Item kumquatSapling;
    public static Item peachSapling;
    public static Item coconutSapling;
    public static Item nutmegSapling;
    public static Item figSapling;
    public static Item nectarineSapling;
    public static Item mangoSapling;
    public static Item dragonFruitSapling;
    public static Item starFruitSapling;
    public static Item avocadoSapling;
    public static Item apricotSapling;
    public static Item pearSapling;
    public static Item limeSapling;
    public static Item dateSapling;
    public static Item almondSapling;
    public static Item cashewSapling;
    public static Item pecanSapling;
    public static Item walnutSapling;

    // secondary ingredients?
    public static Item oliveOil;
    public static Item cheese;
    public static Item flour;
    public static Item butter;
    public static Item noodle;
    public static Item tofu;
    public static Item molasses;
    public static Item caramel;
    public static Item chocolate;
    public static Item tortilla;
    public static Item soySauce;
    public static Item dough;
    public static Item ravioli;
    public static Item salsa;
    public static Item artichokeDip;
    public static Item pepperoni;

    // drinks
    public static Item grapeJuice;
    public static Item orangeJuice;
    public static Item appleJuice;
    public static Item cranberryJuice;
    public static Item saguaroJuice;
    public static Item tomatoJuice;
    public static Item melonJuice;
    public static Item pineappleJuice;
    public static Item coffee;
    public static Item lemonade;
    public static Item limeade;
    public static Item soyMilk;
    //public static Item tea;

    public static Item strawberrySmoothie;
    public static Item bananaSmoothie;
    public static Item kaleSmoothie;
    public static Item fruitSmoothie;

    public static Item chocolateMilkshake;

    public static Item beer;
    public static Item wine;
    public static Item mead;
    public static Item rum;
    public static Item pumpkinSpiceLatte;

    // jams
    public static Item grapeJam;
    public static Item strawberryJam;
    public static Item peachJam;
    public static Item apricotJam;
    public static Item blackberryJam;
    public static Item blueberryJam;
    public static Item cherryJam;
    public static Item elderberryJam;
    public static Item raspberryJam;

    // snacks?
    public static Item beefJerky;
    public static Item porkJerky;
    public static Item kaleChips;
    public static Item potatoChips;
    public static Item steamedRice;
    public static Item frenchFries;
    public static Item sweetPotatoFries;
    public static Item onionRings;
    public static Item raisins;
    public static Item doughnut;
    public static Item popcorn;
    public static Item bakedBeans;
    public static Item toast;
    public static Item cucumberSalad;
    public static Item caesarSalad;
    public static Item leafySalad;
    public static Item fruitSalad;
    public static Item veggieSalad;
    public static Item porkAndBeans;
    public static Item oatmeal;
    public static Item leekSoup;
    public static Item yoghurt;
    public static Item saucyChips;
    public static Item roastedNuts;
    public static Item trailMix;
    public static Item proteinBar;
    public static Item nougat;

    // breakfast
    public static Item scrambledEggs;
    public static Item butteredToast;
    public static Item toastWithJam;


    // meals
    public static Item hamSandwich;
    public static Item peanutButterAndJam;
    public static Item BLT;
    public static Item grilledCheese;
    public static Item tunaSandwich;
    public static Item cheeseburger;
    public static Item hamburger;
    public static Item tofuBurger;
    public static Item pizza;
    public static Item supremePizza;
    public static Item cheesePizza;
    public static Item pineapplePepperoniPizza;
    public static Item lemonChicken;
    public static Item friedChicken;
    public static Item chickenAndNoodles;
    public static Item chickenAndDumplings;
    public static Item tofuAndDumplings;
    public static Item spaghettiSquash;
    public static Item chickenAndRice;
    public static Item taco;
    public static Item sushi;
    public static Item eggRoll;
    public static Item cashewChicken;

    // desert block?
    public static Item coffeeCake;
    public static Item chocolateCake;
    public static Item fruitCake;
    public static Item strawberryShortCake;
    public static Item carrotCake;
    public static Item turtleCake;

    // desert item
    public static Item applePie;
    public static Item yamJam;
    public static Item bananaCreamPie;
    public static Item candyCorn;
    public static Item vanillaIceCream;
    public static Item strawberryIceCream;
    public static Item mangoIceCream;
    public static Item rumRaisinIceCream;
    public static Item pecanIceCream;
    public static Item cherryPie;
    public static Item cheeseCake;
    public static Item brownies;
    public static Item snickerDoodle;
    public static Item bananaNutBread;
    public static Item pecanPie;
    public static Item candiedNuts;
    public static Item almondBrittle;
    public static Item oatmealCookie;
    public static Item nuttyCookie;
    public static Item praline;

    public static Item burrito;
    public static Item tostada;
    public static Item horchata;
    public static Item carnitas;
    public static Item fajitas;
    public static Item enchilada;
    public static Item churros;
    public static Item tamales;
    public static Item tresLecheCake;
    public static Item stuffedPoblanos;
    public static Item chiliRelleno;
    public static Item crema;
    public static Item refriedBeans;
    public static Item chimichanga;
    public static Item quesadilla;

    // cooking utensils?
    public static Item foodPress;
    public static Item fryingPan;
    public static Item cookingPot;
    public static Item mortarAndPestle;

    public static Item saltOre;


    public static Item guide;


    public static void init(RegistryEvent.Register<Item> itemRegister) {
        guide = registerItem(itemRegister, ItemNames.GUIDE, new GuideBookItem(createGroup()));

        artichoke = registerItem(itemRegister, ItemNames.ARTICHOKE, new Item(createGroup().food(EDIBLE_1)));
        asparagus = registerItem(itemRegister, ItemNames.ASPARAGUS, new Item(createGroup().food(EDIBLE_3)));
        barley = registerItem(itemRegister, ItemNames.BARLEY, new Item(createGroup().food(EDIBLE_1)));
        bellPepper = registerItem(itemRegister, ItemNames.BELLPEPPER, new Item(createGroup().food(EDIBLE_3)));
        blackBean = registerItem(itemRegister, ItemNames.BLACKBEAN, new Item(createGroup().food(EDIBLE_3)));
        blackberry = registerItem(itemRegister, ItemNames.BLACKBERRY, new Item(createGroup().food(EDIBLE_3)));
        blueberry = registerItem(itemRegister, ItemNames.BLUEBERRY, new Item(createGroup().food(EDIBLE_3)));
        broccoli = registerItem(itemRegister, ItemNames.BROCCOLI, new Item(createGroup().food(EDIBLE_3)));
        cabbage = registerItem(itemRegister, ItemNames.CABBAGE, new Item(createGroup().food(EDIBLE_1)));
        cantaloupe = registerItem(itemRegister, ItemNames.CANTALOUPE, new Item(createGroup().food(EDIBLE_3)));
        cauliflower = registerItem(itemRegister, ItemNames.CAULIFLOWER, new Item(createGroup().food(EDIBLE_3)));
        celery = registerItem(itemRegister, ItemNames.CELERY, new Item(createGroup().food(EDIBLE_3)));
        coffeeBeans = registerItem(itemRegister, ItemNames.COFFEE_BEANS, new Item(createGroup().food(EDIBLE_3)));
        corn = registerItem(itemRegister, ItemNames.CORN, new Item(createGroup().food(EDIBLE_3)));
        cranberry = registerItem(itemRegister, ItemNames.CRANBERRY, new Item(createGroup().food(EDIBLE_3)));
        cucumber = registerItem(itemRegister, ItemNames.CUCUMBER, new Item(createGroup().food(EDIBLE_3)));
        currant = registerItem(itemRegister, ItemNames.CURRANT, new Item(createGroup().food(EDIBLE_3)));
        eggplant = registerItem(itemRegister, ItemNames.EGGPLANT, new Item(createGroup().food(EDIBLE_3)));
        elderberry = registerItem(itemRegister, ItemNames.ELDERBERRY, new Item(createGroup().food(EDIBLE_3)));
        garlic = registerItem(itemRegister, ItemNames.GARLIC, new Item(createGroup().food(EDIBLE_1)));
        grape = registerItem(itemRegister, ItemNames.GRAPE, new Item(createGroup().food(EDIBLE_3)));
        greenBean = registerItem(itemRegister, ItemNames.GREENBEAN, new Item(createGroup().food(EDIBLE_3)));
        greenOnion = registerItem(itemRegister, ItemNames.GREENONION, new Item(createGroup().food(EDIBLE_1)));
        honeydew = registerItem(itemRegister, ItemNames.HONEYDEW, new Item(createGroup().food(EDIBLE_3)));
        hops = registerItem(itemRegister, ItemNames.HOPS, new Item(createGroup()));
        kale = registerItem(itemRegister, ItemNames.KALE, new Item(createGroup().food(EDIBLE_3)));
        kiwi = registerItem(itemRegister, ItemNames.KIWI, new Item(createGroup().food(EDIBLE_3)));
        leek = registerItem(itemRegister, ItemNames.LEEK, new Item(createGroup().food(EDIBLE_3)));
        lettuce = registerItem(itemRegister, ItemNames.LETTUCE, new Item(createGroup().food(EDIBLE_3)));
        oat = registerItem(itemRegister, ItemNames.OAT, new Item(createGroup().food(EDIBLE_1)));
        olive = registerItem(itemRegister, ItemNames.OLIVE, new Item(createGroup().food(EDIBLE_3)));
        onion = registerItem(itemRegister, ItemNames.ONION, new Item(createGroup().food(EDIBLE_3)));
        peanut = registerItem(itemRegister, ItemNames.PEANUT, new Item(createGroup().food(EDIBLE_1)));
        pineapple = registerItem(itemRegister, ItemNames.PINEAPPLE, new Item(createGroup().food(EDIBLE_3)));
        radish = registerItem(itemRegister, ItemNames.RADISH, new Item(createGroup().food(EDIBLE_3)));
        raspberry = registerItem(itemRegister, ItemNames.RASPBERRY, new Item(createGroup().food(EDIBLE_3)));
        rhubarb = registerItem(itemRegister, ItemNames.RHUBARB, new Item(createGroup().food(EDIBLE_3)));
        rice = registerItem(itemRegister, ItemNames.RICE, new Item(createGroup().food(EDIBLE_1)));
        rutabaga = registerItem(itemRegister, ItemNames.RUTABAGA, new Item(createGroup().food(EDIBLE_3)));
        saguaro = registerItem(itemRegister, ItemNames.SAGUARO, new Item(createGroup().food(EDIBLE_3)));
        soybean = registerItem(itemRegister, ItemNames.SOYBEAN, new Item(createGroup().food(EDIBLE_1)));
        spinach = registerItem(itemRegister, ItemNames.SPINACH, new Item(createGroup().food(EDIBLE_3)));
        squash = registerItem(itemRegister, ItemNames.SQUASH, new Item(createGroup().food(EDIBLE_3)));
        strawberry = registerItem(itemRegister, ItemNames.STRAWBERRY, new Item(createGroup().food(EDIBLE_3)));
        sweetPotato = registerItem(itemRegister, ItemNames.SWEETPOTATO, new Item(createGroup().food(EDIBLE_3)));
        tomatillo = registerItem(itemRegister, ItemNames.TOMATILLO, new Item(createGroup().food(EDIBLE_3)));
        tomato = registerItem(itemRegister, ItemNames.TOMATO, new Item(createGroup().food(EDIBLE_3)));
        turnip = registerItem(itemRegister, ItemNames.TURNIP, new Item(createGroup().food(EDIBLE_3)));
        yam = registerItem(itemRegister, ItemNames.YAM, new Item(createGroup().food(EDIBLE_3)));
        zucchini = registerItem(itemRegister, ItemNames.ZUCCHINI, new Item(createGroup().food(EDIBLE_3)));

        orange = registerItem(itemRegister, ItemNames.ORANGE, new Item(createGroup().food(EDIBLE_3)));
        banana = registerItem(itemRegister, ItemNames.BANANA, new Item(createGroup().food(EDIBLE_3)));
        persimmon = registerItem(itemRegister, ItemNames.PERSIMMON, new Item(createGroup().food(EDIBLE_3)));
        plum = registerItem(itemRegister, ItemNames.PLUM, new Item(createGroup().food(EDIBLE_3)));
        cherry = registerItem(itemRegister, ItemNames.CHERRY, new Item(createGroup().food(EDIBLE_3)));
        lemon = registerItem(itemRegister, ItemNames.LEMON, new Item(createGroup().food(EDIBLE_3)));
        grapefruit = registerItem(itemRegister, ItemNames.GRAPEFRUIT, new Item(createGroup().food(EDIBLE_3)));
        kumquat = registerItem(itemRegister, ItemNames.KUMQUAT, new Item(createGroup().food(EDIBLE_3)));
        peach = registerItem(itemRegister, ItemNames.PEACH, new Item(createGroup().food(EDIBLE_3)));
        coconut = registerItem(itemRegister, ItemNames.COCONUT, new Item(createGroup().food(EDIBLE_1)));
        nutmeg = registerItem(itemRegister, ItemNames.NUTMEG, new Item(createGroup().food(EDIBLE_1)));
        fig = registerItem(itemRegister, ItemNames.FIG, new Item(createGroup().food(EDIBLE_3)));
        nectarine = registerItem(itemRegister, ItemNames.NECTARINE, new Item(createGroup().food(EDIBLE_3)));
        mango = registerItem(itemRegister, ItemNames.MANGO, new Item(createGroup().food(EDIBLE_3)));
        dragonFruit = registerItem(itemRegister, ItemNames.DRAGONFRUIT, new Item(createGroup().food(EDIBLE_3)));
        starFruit = registerItem(itemRegister, ItemNames.STARFRUIT, new Item(createGroup().food(EDIBLE_3)));
        avocado = registerItem(itemRegister, ItemNames.AVOCADO, new Item(createGroup().food(EDIBLE_3)));
        apricot = registerItem(itemRegister, ItemNames.APRICOT, new Item(createGroup().food(EDIBLE_3)));
        pear = registerItem(itemRegister, ItemNames.PEAR, new Item(createGroup().food(EDIBLE_3)));
        lime = registerItem(itemRegister, ItemNames.LIME, new Item(createGroup().food(EDIBLE_3)));
        date = registerItem(itemRegister, ItemNames.DATE, new Item(createGroup().food(EDIBLE_3)));
        almond = registerItem(itemRegister, ItemNames.ALMOND, new Item(createGroup().food(EDIBLE_3)));
        cashew = registerItem(itemRegister, ItemNames.CASHEW, new Item(createGroup().food(EDIBLE_1)));
        pecan = registerItem(itemRegister, ItemNames.PECAN, new Item(createGroup().food(EDIBLE_3)));
        walnut = registerItem(itemRegister, ItemNames.WALNUT, new Item(createGroup().food(EDIBLE_3)));

        mustard = registerItem(itemRegister, ItemNames.MUSTARD, new Item(createGroup()));
        vanilla = registerItem(itemRegister, ItemNames.VANILLA, new Item(createGroup()));
        paprika = registerItem(itemRegister, ItemNames.PAPRIKA, new Item(createGroup())); // TODO need recipe to make paprika in future update
        chilePepper = registerItem(itemRegister, ItemNames.CHILE_PEPPER, new Item(createGroup()));
        salt = registerItem(itemRegister, ItemNames.SALT, new Item(createGroup()));
        turmeric = registerItem(itemRegister, ItemNames.TURMERIC, new Item(createGroup()));
        ginger = registerItem(itemRegister, ItemNames.GINGER, new Item(createGroup()));
        basil = registerItem(itemRegister, ItemNames.BASIL, new Item(createGroup().food(EDIBLE_1)));

        artichokeSeed = registerItem(itemRegister, ItemNames.ARTICHOKE_SEED, new SeedItem(BlockRegistry.artichokeCropBlock, createGroup(), SWAMP));
        asparagusSeed = registerItem(itemRegister, ItemNames.ASPARAGUS_SEED, new SeedItem(BlockRegistry.asparagusCropBlock, createGroup(), SWAMP));
        bellPepperSeed = registerItem(itemRegister, ItemNames.BELLPEPPER_SEED, new SeedItem(BlockRegistry.bellPepperCropBlock, createGroup(), PLAINS));
        blackBeanSeed = registerItem(itemRegister, ItemNames.BLACKBEAN_SEED, new SeedItem(BlockRegistry.blackBeanCropBlock, createGroup(), FOREST));
        blackberrySeed = registerItem(itemRegister, ItemNames.BLACKBERRY_SEED, new SeedItem(BlockRegistry.blackberryCropBlock, createGroup(), FOREST));
        blueberrySeed = registerItem(itemRegister, ItemNames.BLUEBERRY_SEED, new SeedItem(BlockRegistry.blueberryCropBlock, createGroup(), FOREST));
        broccoliSeed = registerItem(itemRegister, ItemNames.BROCCOLI_SEED, new SeedItem(BlockRegistry.broccoliCropBlock, createGroup(), PLAINS));
        cabbageSeed = registerItem(itemRegister, ItemNames.CABBAGE_SEED, new SeedItem(BlockRegistry.cabbageCropBlock, createGroup(), PLAINS));
        cantaloupeSeed = registerItem(itemRegister, ItemNames.CANTALOUPE_SEED, new SeedItem(BlockRegistry.cantaloupeCropBlock, createGroup(), FOREST));
        cauliflowerSeed = registerItem(itemRegister, ItemNames.CAULIFLOWER_SEED, new SeedItem(BlockRegistry.cauliflowerCropBlock, createGroup(), FOREST));
        celerySeed = registerItem(itemRegister, ItemNames.CELERY_SEED, new SeedItem(BlockRegistry.celeryCropBlock, createGroup(), FOREST));
        coffeeSeed = registerItem(itemRegister, ItemNames.COFFEE_SEED, new SeedItem(BlockRegistry.coffeeCropBlock, createGroup(), JUNGLE));
        cornSeed = registerItem(itemRegister, ItemNames.CORN_SEED, new SeedItem(BlockRegistry.cornCropBlock, createGroup(), PLAINS));
        cranberrySeed = registerItem(itemRegister, ItemNames.CRANBERRY_SEED, new SeedItem(BlockRegistry.cranberryCropBlock, createGroup(), SWAMP));
        cucumberSeed = registerItem(itemRegister, ItemNames.CUCUMBER_SEED, new SeedItem(BlockRegistry.cucumberCropBlock, createGroup(), PLAINS));
        currantSeed = registerItem(itemRegister, ItemNames.CURRANT_SEED, new SeedItem(BlockRegistry.currantCropBlock, createGroup(), SWAMP));
        eggplantSeed = registerItem(itemRegister, ItemNames.EGGPLANT_SEED, new SeedItem(BlockRegistry.eggplantCropBlock, createGroup(), JUNGLE));
        elderberrySeed = registerItem(itemRegister, ItemNames.ELDERBERRY_SEED, new SeedItem(BlockRegistry.elderberryCropBlock, createGroup(), FOREST));
        garlicSeed = registerItem(itemRegister, ItemNames.GARLIC_SEED, new SeedItem(BlockRegistry.garlicCropBlock, createGroup(), JUNGLE));
        grapeSeed = registerItem(itemRegister, ItemNames.GRAPE_SEED, new SeedItem(BlockRegistry.grapeCropBlock, createGroup(), FOREST));
        greenBeanSeed = registerItem(itemRegister, ItemNames.GREENBEAN_SEED, new SeedItem(BlockRegistry.greenBeanCropBlock, createGroup(), PLAINS));
        greenOnionSeed = registerItem(itemRegister, ItemNames.GREENONION_SEED, new SeedItem(BlockRegistry.greenOnionCropBlock, createGroup(), JUNGLE));
        honeydewSeed = registerItem(itemRegister, ItemNames.HONEYDEW_SEED,new SeedItem(BlockRegistry.honeydewCropBlock, createGroup(), JUNGLE));
        hopsSeed = registerItem(itemRegister, ItemNames.HOPS_SEED, new SeedItem(BlockRegistry.hopsCropBlock, createGroup(), SAVANNA));
        kaleSeed = registerItem(itemRegister, ItemNames.KALE_SEED, new SeedItem(BlockRegistry.kaleCropBlock, createGroup(), PLAINS));
        kiwiSeed = registerItem(itemRegister, ItemNames.KIWI_SEED, new SeedItem(BlockRegistry.kiwiCropBlock, createGroup(), SAVANNA));
        leekSeed = registerItem(itemRegister, ItemNames.LEEK_SEED, new SeedItem(BlockRegistry.leekCropBlock, createGroup(), SAVANNA));
        lettuceSeed = registerItem(itemRegister, ItemNames.LETTUCE_SEED,new SeedItem(BlockRegistry.lettuceCropBlock, createGroup(), PLAINS));
        oliveSeed = registerItem(itemRegister, ItemNames.OLIVE_SEED, new SeedItem(BlockRegistry.oliveCropBlock, createGroup(), SAVANNA));
        onionSeed = registerItem(itemRegister, ItemNames.ONION_SEED, new SeedItem(BlockRegistry.onionCropBlock, createGroup(), JUNGLE));
        peanutSeed = registerItem(itemRegister, ItemNames.PEANUT_SEED, new SeedItem(BlockRegistry.peanutCropBlock, createGroup(), JUNGLE));
        pineappleSeed = registerItem(itemRegister, ItemNames.PINEAPPLE_SEED, new SeedItem(BlockRegistry.pineappleCropBlock, createGroup(), JUNGLE));
        radishSeed = registerItem(itemRegister, ItemNames.RADISH_SEED, new SeedItem(BlockRegistry.radishCropBlock, createGroup(), FOREST));
        raspberrySeed = registerItem(itemRegister, ItemNames.RASPBERRY_SEED, new SeedItem(BlockRegistry.raspberryCropBlock, createGroup(), FOREST));
        rhubarbSeed = registerItem(itemRegister, ItemNames.RHUBARB_SEED, new SeedItem(BlockRegistry.rhubarbCropBlock, createGroup(), JUNGLE));
        riceSeed = registerItem(itemRegister, ItemNames.RICE_SEED, new SeedItem(BlockRegistry.riceCropBlock, createGroup(), JUNGLE));
        rutabagaSeed = registerItem(itemRegister, ItemNames.RUTABAGA_SEED, new SeedItem(BlockRegistry.rutabagaCropBlock, createGroup(), SAVANNA));
        saguaroSeed = registerItem(itemRegister, ItemNames.SAGUARO_SEED, new SeedItem(BlockRegistry.saguaroCropBlock, createGroup(), DESERT));
        spinachSeed = registerItem(itemRegister, ItemNames.SPINACH_SEED, new SeedItem(BlockRegistry.spinachCropBlock, createGroup(), FOREST));
        squashSeed = registerItem(itemRegister, ItemNames.SQUASH_SEED, new SeedItem(BlockRegistry.squashCropBlock, createGroup(), SAVANNA));
        strawberrySeed = registerItem(itemRegister, ItemNames.STRAWBERRY_SEED, new SeedItem(BlockRegistry.strawberryCropBlock, createGroup(), FOREST));
        sweetPotatoSeed = registerItem(itemRegister, ItemNames.SWEETPOTATO_SEED, new SeedItem(BlockRegistry.sweetPotatoCropBlock, createGroup(), PLAINS));
        tomatilloSeed = registerItem(itemRegister, ItemNames.TOMATILLO_SEED, new SeedItem(BlockRegistry.tomatilloCropBlock, createGroup(), FOREST));
        tomatoSeed = registerItem(itemRegister, ItemNames.TOMATO_SEED, new SeedItem(BlockRegistry.tomatoCropBlock, createGroup(), FOREST));
        turnipSeed = registerItem(itemRegister, ItemNames.TURNIP_SEED, new SeedItem(BlockRegistry.turnipCropBlock, createGroup(), JUNGLE));
        yamSeed = registerItem(itemRegister, ItemNames.YAM_SEED, new SeedItem(BlockRegistry.yamCropBlock, createGroup(), SAVANNA));
        zucchiniSeed = registerItem(itemRegister, ItemNames.ZUCCHINI_SEED, new SeedItem(BlockRegistry.zucchiniCropBlock, createGroup(), SAVANNA));
        mustardSeed = registerItem(itemRegister, ItemNames.MUSTARD_SEED, new SeedItem(BlockRegistry.mustardCropBlock, createGroup(), PLAINS));
        pepperSeed = registerItem(itemRegister, ItemNames.CHILE_PEPPER_SEED, new SeedItem(BlockRegistry.chilePepperCropBlock, createGroup(), PLAINS));
        turmericSeed = registerItem(itemRegister, ItemNames.TURMERIC_SEED, new SeedItem(BlockRegistry.turmericCropBlock, createGroup(), SAVANNA));
        gingerSeed = registerItem(itemRegister, ItemNames.GINGER_SEED, new SeedItem(BlockRegistry.gingerCropBlock, createGroup(), SAVANNA));
        basilSeed = registerItem(itemRegister, ItemNames.BASIL_SEED, new SeedItem(BlockRegistry.basilCropBlock, createGroup(), JUNGLE));
        oatSeed = registerItem(itemRegister, ItemNames.OAT_SEED, new SeedItem(BlockRegistry.oatCropBlock, createGroup(), PLAINS));
        barleySeed = registerItem(itemRegister, ItemNames.BARLEY_SEED, new SeedItem(BlockRegistry.barleyCropBlock, createGroup(), PLAINS));
        soybeanSeed = registerItem(itemRegister, ItemNames.SOYBEAN_SEED, new SeedItem(BlockRegistry.soybeanCropBlock, createGroup(), PLAINS));

        appleSapling = registerItem(itemRegister, ItemNames.APPLE_SAPLING, new BlockNamedItem(BlockRegistry.appleSaplingBlock, createGroup()));
        bananaSapling = registerItem(itemRegister, ItemNames.BANANA_SAPLING, new BlockNamedItem(BlockRegistry.bananaSaplingBlock, createGroup()));
        orangeSapling = registerItem(itemRegister, ItemNames.ORANGE_SAPLING, new BlockNamedItem(BlockRegistry.orangeSaplingBlock, createGroup()));
        persimmonSapling = registerItem(itemRegister, ItemNames.PERSIMMON_SAPLING, new BlockNamedItem(BlockRegistry.persimmonSaplingBlock, createGroup()));
        plumSapling = registerItem(itemRegister, ItemNames.PLUM_SAPLING, new BlockNamedItem(BlockRegistry.plumSaplingBlock, createGroup()));
        cherrySapling = registerItem(itemRegister, ItemNames.CHERRY_SAPLING, new BlockNamedItem(BlockRegistry.cherrySaplingBlock, createGroup()));
        lemonSapling = registerItem(itemRegister, ItemNames.LEMON_SAPLING, new BlockNamedItem(BlockRegistry.lemonSaplingBlock, createGroup()));
        grapefruitSapling = registerItem(itemRegister, ItemNames.GRAPEFRUIT_SAPLING, new BlockNamedItem(BlockRegistry.grapefruitSaplingBlock, createGroup()));
        kumquatSapling = registerItem(itemRegister, ItemNames.KUMQUAT_SAPLING, new BlockNamedItem(BlockRegistry.kumquatSaplingBlock, createGroup()));
        peachSapling = registerItem(itemRegister, ItemNames.PEACH_SAPLING, new BlockNamedItem(BlockRegistry.peachSaplingBlock, createGroup()));
        coconutSapling = registerItem(itemRegister, ItemNames.COCONUT_SAPLING, new BlockNamedItem(BlockRegistry.coconutSaplingBlock, createGroup()));
        nutmegSapling = registerItem(itemRegister, ItemNames.NUTMEG_SAPLING, new BlockNamedItem(BlockRegistry.nutmegSaplingBlock, createGroup()));
        figSapling = registerItem(itemRegister, ItemNames.FIG_SAPLING, new BlockNamedItem(BlockRegistry.figSaplingBlock, createGroup()));
        nectarineSapling = registerItem(itemRegister, ItemNames.NECTARINE_SAPLING, new BlockNamedItem(BlockRegistry.nectarineSaplingBlock, createGroup()));
        mangoSapling = registerItem(itemRegister, ItemNames.MANGO_SAPLING, new BlockNamedItem(BlockRegistry.mangoSaplingBlock, createGroup()));
        dragonFruitSapling = registerItem(itemRegister, ItemNames.DRAGONFRUIT_SAPLING, new BlockNamedItem(BlockRegistry.dragonFruitSaplingBlock, createGroup()));
        starFruitSapling = registerItem(itemRegister, ItemNames.STARFRUIT_SAPLING, new BlockNamedItem(BlockRegistry.starFruitSaplingBlock, createGroup()));
        avocadoSapling = registerItem(itemRegister, ItemNames.AVOCADO_SAPLING, new BlockNamedItem(BlockRegistry.avocadoSaplingBlock, createGroup()));
        apricotSapling = registerItem(itemRegister, ItemNames.APRICOT_SAPLING, new BlockNamedItem(BlockRegistry.apricotSaplingBlock, createGroup()));
        pearSapling = registerItem(itemRegister, ItemNames.PEAR_SAPLING, new BlockNamedItem(BlockRegistry.pearSaplingBlock, createGroup()));
        limeSapling = registerItem(itemRegister, ItemNames.LIME_SAPLING, new BlockNamedItem(BlockRegistry.limeSaplingBlock, createGroup()));
        dateSapling = registerItem(itemRegister, ItemNames.DATE_SAPLING, new BlockNamedItem(BlockRegistry.dateSaplingBlock, createGroup()));
        almondSapling = registerItem(itemRegister, ItemNames.ALMOND_SAPLING, new BlockNamedItem(BlockRegistry.almondSaplingBlock, createGroup()));
        cashewSapling = registerItem(itemRegister, ItemNames.CASHEW_SAPLING, new BlockNamedItem(BlockRegistry.cashewSaplingBlock, createGroup()));
        pecanSapling = registerItem(itemRegister, ItemNames.PECAN_SAPLING, new BlockNamedItem(BlockRegistry.pecanSaplingBlock, createGroup()));
        walnutSapling = registerItem(itemRegister, ItemNames.WALNUT_SAPLING, new BlockNamedItem(BlockRegistry.walnutSaplingBlock, createGroup()));

        oliveOil = registerItem(itemRegister, ItemNames.OLIVE_OIL, new Item(createGroup()));
        cheese = registerItem(itemRegister, ItemNames.CHEESE, new Item(createGroup().food(EDIBLE_5)));
        flour = registerItem(itemRegister, ItemNames.FLOUR, new Item(createGroup()));
        butter = registerItem(itemRegister, ItemNames.BUTTER, new Item(createGroup().food(EDIBLE_3)));
        noodle = registerItem(itemRegister, ItemNames.NOODLE, new Item(createGroup()));
        tofu = registerItem(itemRegister, ItemNames.TOFU, new Item(createGroup().food(EDIBLE_5)));
        molasses = registerItem(itemRegister, ItemNames.MOLASSES, new Item(createGroup()));
        caramel = registerItem(itemRegister, ItemNames.CARAMEL, new Item(createGroup()));
        chocolate = registerItem(itemRegister, ItemNames.CHOCOLATE, new Item(createGroup().food(EDIBLE_5)));
        tortilla = registerItem(itemRegister, ItemNames.TORTILLA, new Item(createGroup().food(EDIBLE_3)));
        soySauce = registerItem(itemRegister, ItemNames.SOY_SAUCE, new Item(createGroup()));
        dough = registerItem(itemRegister, ItemNames.DOUGH, new Item(createGroup()));
        ravioli = registerItem(itemRegister, ItemNames.RAVIOLI, new Item(createGroup()));
        salsa = registerItem(itemRegister, ItemNames.SALSA, new Item(createGroup().food(EDIBLE_3)));
        artichokeDip = registerItem(itemRegister, ItemNames.ARTICHOKE_DIP, new Item(createGroup().food(EDIBLE_3)));
        pepperoni = registerItem(itemRegister, ItemNames.PEPPERONI, new Item(createGroup().food(EDIBLE_5)));


        grapeJuice = registerItem(itemRegister, ItemNames.GRAPE_JUICE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        orangeJuice = registerItem(itemRegister, ItemNames.ORANGE_JUICE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        appleJuice = registerItem(itemRegister, ItemNames.APPLE_JUICE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        cranberryJuice = registerItem(itemRegister, ItemNames.CRANBERRY_JUICE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        saguaroJuice = registerItem(itemRegister, ItemNames.SAGUARO_JUICE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        tomatoJuice = registerItem(itemRegister, ItemNames.TOMATO_JUICE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        melonJuice = registerItem(itemRegister, ItemNames.MELON_JUICE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        pineappleJuice = registerItem(itemRegister, ItemNames.PINEAPPLE_JUICE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        coffee = registerItem(itemRegister, ItemNames.COFFEE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        lemonade = registerItem(itemRegister, ItemNames.LEMONADE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        limeade = registerItem(itemRegister, ItemNames.LIMEADE, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        soyMilk = registerItem(itemRegister, ItemNames.SOY_MILK, new Drink(createGroup().food(EDIBLE_5_BUILDER.setAlwaysEdible().build()).containerItem(Items.GLASS_BOTTLE)));
        strawberrySmoothie = registerItem(itemRegister, ItemNames.STRAWBERRY_SMOOTHIE, new Drink(createGroup().food(EDIBLE_7_BUILDER.setAlwaysEdible().build())));
        bananaSmoothie = registerItem(itemRegister, ItemNames.BANANA_SMOOTHIE, new Drink(createGroup().food(EDIBLE_7_BUILDER.setAlwaysEdible().build())));
        kaleSmoothie = registerItem(itemRegister, ItemNames.KALE_SMOOTHIE, new Drink(createGroup().food(EDIBLE_14_BUILDER.setAlwaysEdible().build())));
        fruitSmoothie = registerItem(itemRegister, ItemNames.FRUIT_SMOOTHIE, new Drink(createGroup().food(EDIBLE_7_BUILDER.setAlwaysEdible().build())));
        chocolateMilkshake = registerItem(itemRegister, ItemNames.CHOCOLATE_MILKSHAKE, new Drink(createGroup().food(EDIBLE_7_BUILDER.setAlwaysEdible().build())));
        beer = registerItem(itemRegister, ItemNames.BEER, new Drink(createGroup().food(EDIBLE_7_BUILDER.setAlwaysEdible().build())));
        wine = registerItem(itemRegister, ItemNames.WINE, new Drink(createGroup().food(EDIBLE_7_BUILDER.setAlwaysEdible().build())));
        mead = registerItem(itemRegister, ItemNames.MEAD, new Drink(createGroup().food(EDIBLE_7_BUILDER.setAlwaysEdible().build())));
        rum = registerItem(itemRegister, ItemNames.RUM, new Drink(createGroup().food(EDIBLE_7_BUILDER.setAlwaysEdible().build())));
        pumpkinSpiceLatte = registerItem(itemRegister, ItemNames.PUMPKIN_SPICE_LATTE, new Drink(createGroup().food(EDIBLE_14_BUILDER.setAlwaysEdible().build())));
        grapeJam = registerItem(itemRegister, ItemNames.GRAPE_JAM, new Drink(createGroup().food(EDIBLE_3_BUILDER.setAlwaysEdible().build())));
        strawberryJam = registerItem(itemRegister, ItemNames.STRAWBERRY_JAM, new Drink(createGroup().food(EDIBLE_3_BUILDER.setAlwaysEdible().build())));
        peachJam = registerItem(itemRegister, ItemNames.PEACH_JAM, new Drink(createGroup().food(EDIBLE_3_BUILDER.setAlwaysEdible().build())));
        apricotJam = registerItem(itemRegister, ItemNames.APRICOT_JAM, new Drink(createGroup().food(EDIBLE_3_BUILDER.setAlwaysEdible().build())));
        blackberryJam = registerItem(itemRegister, ItemNames.BLACKBERRY_JAM, new Drink(createGroup().food(EDIBLE_3_BUILDER.setAlwaysEdible().build())));
        blueberryJam = registerItem(itemRegister, ItemNames.BLUEBERRY_JAM, new Drink(createGroup().food(EDIBLE_3_BUILDER.setAlwaysEdible().build())));
        cherryJam = registerItem(itemRegister, ItemNames.CHERRY_JAM, new Drink(createGroup().food(EDIBLE_3_BUILDER.setAlwaysEdible().build())));
        elderberryJam = registerItem(itemRegister, ItemNames.ELDERBERRY_JAM, new Drink(createGroup().food(EDIBLE_3_BUILDER.setAlwaysEdible().build())));
        raspberryJam = registerItem(itemRegister, ItemNames.RASPBERRY_JAM, new Drink(createGroup().food(EDIBLE_3_BUILDER.setAlwaysEdible().build())));

        beefJerky = registerItem(itemRegister, ItemNames.BEEF_JERKY, new Item(createGroup().food(EDIBLE_5)));
        porkJerky = registerItem(itemRegister, ItemNames.PORK_JERKY, new Item(createGroup().food(EDIBLE_5)));
        kaleChips = registerItem(itemRegister, ItemNames.KALE_CHIPS, new Item(createGroup().food(EDIBLE_5)));
        potatoChips = registerItem(itemRegister, ItemNames.POTATO_CHIPS, new Item(createGroup().food(EDIBLE_5)));
        steamedRice = registerItem(itemRegister, ItemNames.STEAMED_RICE, new Item(createGroup().food(EDIBLE_5)));
        frenchFries = registerItem(itemRegister, ItemNames.FRENCH_FRIES, new Item(createGroup().food(EDIBLE_5)));
        sweetPotatoFries = registerItem(itemRegister, ItemNames.SWEET_POTATO_FRIES, new Item(createGroup().food(EDIBLE_5)));
        onionRings = registerItem(itemRegister, ItemNames.ONION_RINGS, new Item(createGroup().food(EDIBLE_5)));
        raisins = registerItem(itemRegister, ItemNames.RAISINS, new Item(createGroup().food(EDIBLE_3)));
        doughnut = registerItem(itemRegister, ItemNames.DOUGHNUT, new Item(createGroup().food(EDIBLE_5)));
        popcorn = registerItem(itemRegister, ItemNames.POPCORN, new Item(createGroup().food(EDIBLE_3)));
        bakedBeans = registerItem(itemRegister, ItemNames.BAKED_BEANS, new Item(createGroup().food(EDIBLE_5)));
        toast = registerItem(itemRegister, ItemNames.TOAST, new Item(createGroup().food(EDIBLE_7)));
        cucumberSalad = registerItem(itemRegister, ItemNames.CUCUMBER_SALAD, new Item(createGroup().food(EDIBLE_10)));
        caesarSalad = registerItem(itemRegister, ItemNames.CAESAR_SALAD, new Item(createGroup().food(EDIBLE_10)));
        leafySalad = registerItem(itemRegister, ItemNames.LEAFY_SALAD, new Item(createGroup().food(EDIBLE_10)));
        fruitSalad = registerItem(itemRegister, ItemNames.FRUIT_SALAD, new Item(createGroup().food(EDIBLE_10)));
        veggieSalad = registerItem(itemRegister, ItemNames.VEGGIE_SALAD, new Item(createGroup().food(EDIBLE_10)));
        porkAndBeans = registerItem(itemRegister, ItemNames.PORK_AND_BEANS, new Item(createGroup().food(EDIBLE_10)));
        oatmeal = registerItem(itemRegister, ItemNames.OATMEAL, new Item(createGroup().food(EDIBLE_7)));
        leekSoup = registerItem(itemRegister, ItemNames.LEEK_SOUP, new Item(createGroup().food(EDIBLE_7)));
        yoghurt = registerItem(itemRegister, ItemNames.YOGHURT, new Item(createGroup().food(EDIBLE_5)));
        saucyChips = registerItem(itemRegister, ItemNames.SAUCY_CHIPS, new Item(createGroup().food(EDIBLE_7)));
        roastedNuts = registerItem(itemRegister, ItemNames.ROASTED_NUTS, new Item(createGroup().food(EDIBLE_5)));
        trailMix = registerItem(itemRegister, ItemNames.TRAIL_MIX, new Item(createGroup().food(EDIBLE_10)));
        proteinBar = registerItem(itemRegister, ItemNames.PROTEIN_BAR, new Item(createGroup().food(EDIBLE_10)));
        nougat = registerItem(itemRegister, ItemNames.NOUGAT, new Item(createGroup().food(EDIBLE_7)));

        scrambledEggs = registerItem(itemRegister, ItemNames.SCRAMBLED_EGGS, new Item(createGroup().food(EDIBLE_7)));
        butteredToast = registerItem(itemRegister, ItemNames.BUTTERED_TOAST, new Item(createGroup().food(EDIBLE_7)));
        toastWithJam = registerItem(itemRegister, ItemNames.TOAST_WITH_JAM, new Item(createGroup().food(EDIBLE_7)));

        hamSandwich = registerItem(itemRegister, ItemNames.HAM_SANDWICH, new Item(createGroup().food(EDIBLE_10)));
        peanutButterAndJam = registerItem(itemRegister, ItemNames.PEANUT_BUTTER_AND_JAM, new Item(createGroup().food(EDIBLE_10)));
        BLT = registerItem(itemRegister, ItemNames.BLT, new Item(createGroup().food(EDIBLE_10)));
        grilledCheese = registerItem(itemRegister, ItemNames.GRILLED_CHEESE, new Item(createGroup().food(EDIBLE_7)));
        tunaSandwich = registerItem(itemRegister, ItemNames.TUNA_SANDWICH, new Item(createGroup().food(EDIBLE_10)));
        cheeseburger = registerItem(itemRegister, ItemNames.CHEESEBURGER, new Item(createGroup().food(EDIBLE_10)));
        hamburger = registerItem(itemRegister, ItemNames.HAMBURGER, new Item(createGroup().food(EDIBLE_10)));
        tofuBurger = registerItem(itemRegister, ItemNames.TOFUBURGER, new Item(createGroup().food(EDIBLE_10)));
        pizza = registerItem(itemRegister, ItemNames.PIZZA, new Item(createGroup().food(EDIBLE_10)));
        supremePizza = registerItem(itemRegister, ItemNames.SUPREME_PIZZA, new Item(createGroup().food(EDIBLE_18)));
        cheesePizza = registerItem(itemRegister, ItemNames.CHEESE_PIZZA, new Item(createGroup().food(EDIBLE_14)));
        pineapplePepperoniPizza = registerItem(itemRegister, ItemNames.PINEAPPLE_PEPPERONI_PIZZA, new Item(createGroup().food(EDIBLE_18)));
        lemonChicken = registerItem(itemRegister, ItemNames.LEMON_CHICKEN, new Item(createGroup().food(EDIBLE_10)));
        friedChicken = registerItem(itemRegister, ItemNames.FRIED_CHICKEN, new Item(createGroup().food(EDIBLE_10)));
        chickenAndNoodles = registerItem(itemRegister, ItemNames.CHICKEN_AND_NOODLES, new Item(createGroup().food(EDIBLE_10)));
        chickenAndDumplings = registerItem(itemRegister, ItemNames.CHICKEN_AND_DUMPLINGS, new Item(createGroup().food(EDIBLE_10)));
        tofuAndDumplings = registerItem(itemRegister, ItemNames.TOFU_AND_DUMPLINGS, new Item(createGroup().food(EDIBLE_14)));
        spaghettiSquash = registerItem(itemRegister, ItemNames.SPAGHETTI_SQUASH, new Item(createGroup().food(EDIBLE_10)));
        chickenAndRice = registerItem(itemRegister, ItemNames.CHICKEN_AND_RICE, new Item(createGroup().food(EDIBLE_10)));
        taco = registerItem(itemRegister, ItemNames.TACO, new Item(createGroup().food(EDIBLE_10)));
        sushi = registerItem(itemRegister, ItemNames.SUSHI, new Item(createGroup().food(EDIBLE_10)));
        eggRoll = registerItem(itemRegister, ItemNames.EGG_ROLL, new Item(createGroup().food(EDIBLE_10)));
        cashewChicken = registerItem(itemRegister, ItemNames.CASHEW_CHICKEN, new Item(createGroup().food(EDIBLE_14)));

        applePie = registerItem(itemRegister, ItemNames.APPLE_PIE, new Item(createGroup().food(EDIBLE_14)));
        yamJam = registerItem(itemRegister, ItemNames.YAM_JAM, new Item(createGroup().food(EDIBLE_14)));
        bananaCreamPie = registerItem(itemRegister, ItemNames.BANANA_CREAM_PIE, new Item(createGroup().food(EDIBLE_14)));
        candyCorn = registerItem(itemRegister, ItemNames.CANDY_CORN, new Item(createGroup().food(EDIBLE_5)));
        vanillaIceCream = registerItem(itemRegister, ItemNames.VANILLA_ICE_CREAM, new Item(createGroup().food(EDIBLE_10)));
        strawberryIceCream = registerItem(itemRegister, ItemNames.STRAWBERRY_ICE_CREAM, new Item(createGroup().food(EDIBLE_10)));
        mangoIceCream = registerItem(itemRegister, ItemNames.MANGO_ICE_CREAM, new Item(createGroup().food(EDIBLE_10)));
        rumRaisinIceCream = registerItem(itemRegister, ItemNames.RUM_RAISIN_ICE_CREAM, new Item(createGroup().food(EDIBLE_14)));
        pecanIceCream = registerItem(itemRegister, ItemNames.PECAN_ICE_CREAM, new Item(createGroup().food(EDIBLE_10)));
        cherryPie = registerItem(itemRegister, ItemNames.CHERRY_PIE, new Item(createGroup().food(EDIBLE_14)));
        cheeseCake = registerItem(itemRegister, ItemNames.CHEESE_CAKE, new Item(createGroup().food(EDIBLE_14)));
        brownies = registerItem(itemRegister, ItemNames.BROWNIES, new Item(createGroup().food(EDIBLE_10)));
        snickerDoodle = registerItem(itemRegister, ItemNames.SNICKER_DOODLE, new Item(createGroup().food(EDIBLE_7)));
        bananaNutBread = registerItem(itemRegister, ItemNames.BANANA_NUT_BREAD, new Item(createGroup().food(EDIBLE_10)));
        pecanPie = registerItem(itemRegister, ItemNames.PECAN_PIE, new Item(createGroup().food(EDIBLE_14)));
        candiedNuts = registerItem(itemRegister, ItemNames.CANDIED_NUTS, new Item(createGroup().food(EDIBLE_5)));
        almondBrittle = registerItem(itemRegister, ItemNames.ALMOND_BRITTLE, new Item(createGroup().food(EDIBLE_7)));
        oatmealCookie = registerItem(itemRegister, ItemNames.RAISIN_OATMEAL_COOKIE, new Item(createGroup().food(EDIBLE_5)));
        nuttyCookie = registerItem(itemRegister, ItemNames.NUTTY_COOKIE, new Item(createGroup().food(EDIBLE_5)));
        //praline = registerItem(itemRegister, ItemNames.PRA)

        burrito = registerItem(itemRegister, ItemNames.BURRITO, new Item(createGroup().food(EDIBLE_10)));
        tostada = registerItem(itemRegister, ItemNames.TOSTADA, new Item(createGroup().food(EDIBLE_10)));
        horchata = registerItem(itemRegister, ItemNames.HORCHATA, new Item(createGroup().food(EDIBLE_10)));
        carnitas = registerItem(itemRegister, ItemNames.CARNITAS, new Item(createGroup().food(EDIBLE_10)));
        fajitas = registerItem(itemRegister, ItemNames.FAJITAS, new Item(createGroup().food(EDIBLE_10)));
        enchilada = registerItem(itemRegister, ItemNames.ENCHILADA, new Item(createGroup().food(EDIBLE_10)));
        churros = registerItem(itemRegister, ItemNames.CHURROS, new Item(createGroup().food(EDIBLE_5)));
        tamales = registerItem(itemRegister, ItemNames.TAMALES, new Item(createGroup().food(EDIBLE_14)));
        tresLecheCake = registerItem(itemRegister, ItemNames.TRES_LECHE_CAKE, new Item(createGroup().food(EDIBLE_18)));
        stuffedPoblanos = registerItem(itemRegister, ItemNames.STUFFED_POBLANOS, new Item(createGroup().food(EDIBLE_14)));
        chiliRelleno = registerItem(itemRegister, ItemNames.CHILI_RELLENO, new Item(createGroup().food(EDIBLE_14)));
        crema = registerItem(itemRegister, ItemNames.CREMA, new Item(createGroup().food(EDIBLE_3)));
        refriedBeans = registerItem(itemRegister, ItemNames.REFRIED_BEANS, new Item(createGroup().food(EDIBLE_7)));
        chimichanga = registerItem(itemRegister, ItemNames.CHIMICHANGA, new Item(createGroup().food(EDIBLE_14)));
        quesadilla = registerItem(itemRegister, ItemNames.QUESADILLA, new Item(createGroup().food(EDIBLE_10)));


        foodPress = registerItem(itemRegister, ItemNames.FOOD_PRESS, new Item(createGroup().maxStackSize(1).defaultMaxDamage(500)));
        fryingPan = registerItem(itemRegister, ItemNames.FRYING_PAN, new SwordItem(ItemTier.IRON, 5, -2.0F, createGroup().maxStackSize(1).defaultMaxDamage(500)));
        cookingPot = registerItem(itemRegister, ItemNames.COOKING_POT, new Item(createGroup().maxStackSize(1).defaultMaxDamage(500)));
        mortarAndPestle = registerItem(itemRegister, ItemNames.MORTAR_AND_PESTLE, new Item(createGroup().maxStackSize(1).defaultMaxDamage(500)));

        saltOre = registerItem(itemRegister, ItemNames.SALT_ORE, new BlockNamedItem(BlockRegistry.salt, createGroup()));
    }

    public static Item.Properties createGroup() {
        return new Item.Properties().group(CROPTOPIA_ITEM_GROUP);
    }
}
