package com.epherical.croptopia.datagen;

import com.epherical.croptopia.register.Content;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.client.model.generators.BlockStateProvider;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.client.model.generators.ModelProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

import static com.epherical.croptopia.CroptopiaMod.MODID;

public class CroptopiaItemModelProvider extends BlockStateProvider {


    public CroptopiaItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, MODID, existingFileHelper);
    }

    protected void registerItemModels(ItemModelProvider provider) {
        provider.basicItem(Content.ARTICHOKE.asItem());
        provider.basicItem(Content.ASPARAGUS.asItem());
        provider.basicItem(Content.BARLEY.asItem());
        provider.basicItem(Content.BASIL.asItem());
        provider.basicItem(Content.BELLPEPPER.asItem());
        provider.basicItem(Content.BLACKBEAN.asItem());
        provider.basicItem(Content.BLACKBERRY.asItem());
        provider.basicItem(Content.BLUEBERRY.asItem());
        provider.basicItem(Content.BROCCOLI.asItem());
        provider.basicItem(Content.CABBAGE.asItem());
        provider.basicItem(Content.CANTALOUPE.asItem());
        provider.basicItem(Content.CAULIFLOWER.asItem());
        provider.basicItem(Content.CELERY.asItem());
        provider.basicItem(Content.CHILE_PEPPER.asItem());
        provider.basicItem(Content.COFFEE_BEANS.asItem());
        provider.basicItem(Content.CORN.asItem());
        provider.basicItem(Content.CRANBERRY.asItem());
        provider.basicItem(Content.CUCUMBER.asItem());
        provider.basicItem(Content.CURRANT.asItem());
        provider.basicItem(Content.EGGPLANT.asItem());
        provider.basicItem(Content.ELDERBERRY.asItem());
        provider.basicItem(Content.GARLIC.asItem());
        provider.basicItem(Content.GINGER.asItem());
        provider.basicItem(Content.GRAPE.asItem());
        provider.basicItem(Content.GREENBEAN.asItem());
        provider.basicItem(Content.GREENONION.asItem());
        provider.basicItem(Content.HONEYDEW.asItem());
        provider.basicItem(Content.HOPS.asItem());
        provider.basicItem(Content.KALE.asItem());
        provider.basicItem(Content.KIWI.asItem());
        provider.basicItem(Content.LEEK.asItem());
        provider.basicItem(Content.LETTUCE.asItem());
        provider.basicItem(Content.MUSTARD.asItem());
        provider.basicItem(Content.OAT.asItem());
        provider.basicItem(Content.OLIVE.asItem());
        provider.basicItem(Content.ONION.asItem());
        provider.basicItem(Content.PEANUT.asItem());
        provider.basicItem(Content.PEPPER.asItem());
        provider.basicItem(Content.PINEAPPLE.asItem());
        provider.basicItem(Content.RADISH.asItem());
        provider.basicItem(Content.RASPBERRY.asItem());
        provider.basicItem(Content.RHUBARB.asItem());
        provider.basicItem(Content.RICE.asItem());
        provider.basicItem(Content.RUTABAGA.asItem());
        provider.basicItem(Content.SAGUARO.asItem());
        provider.basicItem(Content.SOYBEAN.asItem());
        provider.basicItem(Content.SPINACH.asItem());
        provider.basicItem(Content.SQUASH.asItem());
        provider.basicItem(Content.STRAWBERRY.asItem());
        provider.basicItem(Content.SWEETPOTATO.asItem());
        provider.basicItem(Content.TEA_LEAVES.asItem());
        provider.basicItem(Content.TOMATILLO.asItem());
        provider.basicItem(Content.TOMATO.asItem());
        provider.basicItem(Content.TURMERIC.asItem());
        provider.basicItem(Content.TURNIP.asItem());
        provider.basicItem(Content.VANILLA.asItem());
        provider.basicItem(Content.YAM.asItem());
        provider.basicItem(Content.ZUCCHINI.asItem());

        provider.basicItem(Content.ARTICHOKE.getSeedItem());
        provider.basicItem(Content.ASPARAGUS.getSeedItem());
        provider.basicItem(Content.BARLEY.getSeedItem());
        provider.basicItem(Content.BASIL.getSeedItem());
        provider.basicItem(Content.BELLPEPPER.getSeedItem());
        provider.basicItem(Content.BLACKBEAN.getSeedItem());
        provider.basicItem(Content.BLACKBERRY.getSeedItem());
        provider.basicItem(Content.BLUEBERRY.getSeedItem());
        provider.basicItem(Content.BROCCOLI.getSeedItem());
        provider.basicItem(Content.CABBAGE.getSeedItem());
        provider.basicItem(Content.CANTALOUPE.getSeedItem());
        provider.basicItem(Content.CAULIFLOWER.getSeedItem());
        provider.basicItem(Content.CELERY.getSeedItem());
        provider.basicItem(Content.CHILE_PEPPER.getSeedItem());
        provider.basicItem(Content.COFFEE_BEANS.getSeedItem());
        provider.basicItem(Content.CORN.getSeedItem());
        provider.basicItem(Content.CRANBERRY.getSeedItem());
        provider.basicItem(Content.CUCUMBER.getSeedItem());
        provider.basicItem(Content.CURRANT.getSeedItem());
        provider.basicItem(Content.EGGPLANT.getSeedItem());
        provider.basicItem(Content.ELDERBERRY.getSeedItem());
        provider.basicItem(Content.GARLIC.getSeedItem());
        provider.basicItem(Content.GINGER.getSeedItem());
        provider.basicItem(Content.GRAPE.getSeedItem());
        provider.basicItem(Content.GREENBEAN.getSeedItem());
        provider.basicItem(Content.GREENONION.getSeedItem());
        provider.basicItem(Content.HONEYDEW.getSeedItem());
        provider.basicItem(Content.HOPS.getSeedItem());
        provider.basicItem(Content.KALE.getSeedItem());
        provider.basicItem(Content.KIWI.getSeedItem());
        provider.basicItem(Content.LEEK.getSeedItem());
        provider.basicItem(Content.LETTUCE.getSeedItem());
        provider.basicItem(Content.MUSTARD.getSeedItem());
        provider.basicItem(Content.OAT.getSeedItem());
        provider.basicItem(Content.OLIVE.getSeedItem());
        provider.basicItem(Content.ONION.getSeedItem());
        provider.basicItem(Content.PEANUT.getSeedItem());
        provider.basicItem(Content.PEPPER.getSeedItem());
        provider.basicItem(Content.PINEAPPLE.getSeedItem());
        provider.basicItem(Content.RADISH.getSeedItem());
        provider.basicItem(Content.RASPBERRY.getSeedItem());
        provider.basicItem(Content.RHUBARB.getSeedItem());
        provider.basicItem(Content.RICE.getSeedItem());
        provider.basicItem(Content.RUTABAGA.getSeedItem());
        provider.basicItem(Content.SAGUARO.getSeedItem());
        provider.basicItem(Content.SOYBEAN.getSeedItem());
        provider.basicItem(Content.SPINACH.getSeedItem());
        provider.basicItem(Content.SQUASH.getSeedItem());
        provider.basicItem(Content.STRAWBERRY.getSeedItem());
        provider.basicItem(Content.SWEETPOTATO.getSeedItem());
        provider.basicItem(Content.TEA_LEAVES.getSeedItem());
        provider.basicItem(Content.TOMATILLO.getSeedItem());
        provider.basicItem(Content.TOMATO.getSeedItem());
        provider.basicItem(Content.TURMERIC.getSeedItem());
        provider.basicItem(Content.TURNIP.getSeedItem());
        provider.basicItem(Content.VANILLA.getSeedItem());
        provider.basicItem(Content.YAM.getSeedItem());
        provider.basicItem(Content.ZUCCHINI.getSeedItem());


        provider.basicItem(Content.ALMOND.asItem());
        //basicItem(Content.APPLE.asItem());
        provider.basicItem(Content.APRICOT.asItem());
        provider.basicItem(Content.AVOCADO.asItem());
        provider.basicItem(Content.BANANA.asItem());
        provider.basicItem(Content.CASHEW.asItem());
        provider.basicItem(Content.CHERRY.asItem());
        provider.basicItem(Content.COCONUT.asItem());
        provider.basicItem(Content.DATE.asItem());
        provider.basicItem(Content.DRAGONFRUIT.asItem());
        provider.basicItem(Content.FIG.asItem());
        provider.basicItem(Content.GRAPEFRUIT.asItem());
        provider.basicItem(Content.KUMQUAT.asItem());
        provider.basicItem(Content.LEMON.asItem());
        provider.basicItem(Content.LIME.asItem());
        provider.basicItem(Content.MANGO.asItem());
        provider.basicItem(Content.NECTARINE.asItem());
        provider.basicItem(Content.NUTMEG.asItem());
        provider.basicItem(Content.ORANGE.asItem());
        provider.basicItem(Content.PEACH.asItem());
        provider.basicItem(Content.PEAR.asItem());
        provider.basicItem(Content.PECAN.asItem());
        provider.basicItem(Content.PERSIMMON.asItem());
        provider.basicItem(Content.PLUM.asItem());
        provider.basicItem(Content.STARFRUIT.asItem());
        provider.basicItem(Content.WALNUT.asItem());
        provider.basicItem(Content.CINNAMON.asItem());

        /*provider.basicItem(Content.ALMOND.getSaplingItem());
        provider.basicItem(Content.APRICOT.getSaplingItem());
        provider.basicItem(Content.AVOCADO.getSaplingItem());
        provider.basicItem(Content.BANANA.getSaplingItem());
        provider.basicItem(Content.CASHEW.getSaplingItem());
        provider.basicItem(Content.CHERRY.getSaplingItem());
        provider.basicItem(Content.COCONUT.getSaplingItem());
        provider.basicItem(Content.DATE.getSaplingItem());
        provider.basicItem(Content.DRAGONFRUIT.getSaplingItem());
        provider.basicItem(Content.FIG.getSaplingItem());
        provider.basicItem(Content.GRAPEFRUIT.getSaplingItem());
        provider.basicItem(Content.KUMQUAT.getSaplingItem());
        provider.basicItem(Content.LEMON.getSaplingItem());
        provider.basicItem(Content.LIME.getSaplingItem());
        provider.basicItem(Content.MANGO.getSaplingItem());
        provider.basicItem(Content.NECTARINE.getSaplingItem());
        provider.basicItem(Content.NUTMEG.getSaplingItem());
        provider.basicItem(Content.ORANGE.getSaplingItem());
        provider.basicItem(Content.PEACH.getSaplingItem());
        provider.basicItem(Content.PEAR.getSaplingItem());
        provider.basicItem(Content.PECAN.getSaplingItem());
        provider.basicItem(Content.PERSIMMON.getSaplingItem());
        provider.basicItem(Content.PLUM.getSaplingItem());
        provider.basicItem(Content.STARFRUIT.getSaplingItem());
        provider.basicItem(Content.WALNUT.getSaplingItem());
        provider.basicItem(Content.CINNAMON.getSapling());*/

        provider.basicItem(Content.ANCHOVY.asItem());
        provider.basicItem(Content.CALAMARI.asItem());
        provider.basicItem(Content.CLAM.asItem());
        provider.basicItem(Content.CRAB.asItem());
        provider.basicItem(Content.GLOWING_CALAMARI.asItem());
        provider.basicItem(Content.OYSTER.asItem());
        provider.basicItem(Content.ROE.asItem());
        provider.basicItem(Content.SHRIMP.asItem());
        provider.basicItem(Content.TUNA.asItem());
        provider.basicItem(Content.BAKED_BEANS.asItem());
        provider.basicItem(Content.BAKED_SWEET_POTATO.asItem());
        provider.basicItem(Content.BAKED_YAM.asItem());
        provider.basicItem(Content.CARAMEL.asItem());
        provider.basicItem(Content.COOKED_ANCHOVY.asItem());
        provider.basicItem(Content.COOKED_BACON.asItem());
        provider.basicItem(Content.COOKED_CALAMARI.asItem());
        provider.basicItem(Content.COOKED_SHRIMP.asItem());
        provider.basicItem(Content.COOKED_TUNA.asItem());
        provider.basicItem(Content.MOLASSES.asItem());
        provider.basicItem(Content.POPCORN.asItem());
        provider.basicItem(Content.RAISINS.asItem());
        provider.basicItem(Content.TOAST.asItem());
        provider.basicItem(Content.APPLE_JUICE.asItem());
        provider.basicItem(Content.CRANBERRY_JUICE.asItem());
        provider.basicItem(Content.GRAPE_JUICE.asItem());
        provider.basicItem(Content.MELON_JUICE.asItem());
        provider.basicItem(Content.ORANGE_JUICE.asItem());
        provider.basicItem(Content.PINEAPPLE_JUICE.asItem());
        provider.basicItem(Content.SAGUARO_JUICE.asItem());
        provider.basicItem(Content.TOMATO_JUICE.asItem());
        provider.basicItem(Content.APRICOT_JAM.asItem());
        provider.basicItem(Content.BLACKBERRY_JAM.asItem());
        provider.basicItem(Content.BLUEBERRY_JAM.asItem());
        provider.basicItem(Content.CHERRY_JAM.asItem());
        provider.basicItem(Content.ELDERBERRY_JAM.asItem());
        provider.basicItem(Content.GRAPE_JAM.asItem());
        provider.basicItem(Content.PEACH_JAM.asItem());
        provider.basicItem(Content.RASPBERRY_JAM.asItem());
        provider.basicItem(Content.STRAWBERRY_JAM.asItem());
        provider.basicItem(Content.BANANA_SMOOTHIE.asItem());
        provider.basicItem(Content.STRAWBERRY_SMOOTHIE.asItem());
        provider.basicItem(Content.MANGO_ICE_CREAM.asItem());
        provider.basicItem(Content.PECAN_ICE_CREAM.asItem());
        provider.basicItem(Content.STRAWBERRY_ICE_CREAM.asItem());
        provider.basicItem(Content.VANILLA_ICE_CREAM.asItem());
        provider.basicItem(Content.APPLE_PIE.asItem());
        provider.basicItem(Content.CHERRY_PIE.asItem());
        provider.basicItem(Content.PECAN_PIE.asItem());
        provider.basicItem(Content.RHUBARB_PIE.asItem());
        provider.basicItem(Content.COOKING_POT.asItem());
        provider.basicItem(Content.FOOD_PRESS.asItem());
        provider.basicItem(Content.FRYING_PAN.asItem());
        provider.basicItem(Content.KNIFE.asItem());
        provider.basicItem(Content.MORTAR_AND_PESTLE.asItem());
        provider.basicItem(Content.PAPRIKA);
        provider.basicItem(Content.SALT);
        provider.basicItem(Content.OLIVE_OIL);
        provider.basicItem(Content.CHEESE);
        provider.basicItem(Content.FLOUR);
        provider.basicItem(Content.BUTTER);
        provider.basicItem(Content.NOODLE);
        provider.basicItem(Content.TOFU);
        provider.basicItem(Content.CHOCOLATE);
        provider.basicItem(Content.TORTILLA);
        provider.basicItem(Content.SOY_SAUCE);
        provider.basicItem(Content.DOUGH);
        provider.basicItem(Content.RAVIOLI);
        provider.basicItem(Content.SALSA);
        provider.basicItem(Content.ARTICHOKE_DIP);
        provider.basicItem(Content.PEPPERONI);
        provider.basicItem(Content.COFFEE);
        provider.basicItem(Content.LEMONADE);
        provider.basicItem(Content.LIMEADE);
        provider.basicItem(Content.SOY_MILK);
        provider.basicItem(Content.KALE_SMOOTHIE);
        provider.basicItem(Content.FRUIT_SMOOTHIE);
        provider.basicItem(Content.CHOCOLATE_MILKSHAKE);
        provider.basicItem(Content.BEER);
        provider.basicItem(Content.WINE);
        provider.basicItem(Content.MEAD);
        provider.basicItem(Content.RUM);
        provider.basicItem(Content.PUMPKIN_SPICE_LATTE);
        provider.basicItem(Content.BEEF_JERKY);
        provider.basicItem(Content.PORK_JERKY);
        provider.basicItem(Content.KALE_CHIPS);
        provider.basicItem(Content.POTATO_CHIPS);
        provider.basicItem(Content.STEAMED_RICE);
        provider.basicItem(Content.FRENCH_FRIES);
        provider.basicItem(Content.SWEET_POTATO_FRIES);
        provider.basicItem(Content.ONION_RINGS);
        provider.basicItem(Content.DOUGHNUT);
        provider.basicItem(Content.CUCUMBER_SALAD);
        provider.basicItem(Content.CAESAR_SALAD);
        provider.basicItem(Content.LEAFY_SALAD);
        provider.basicItem(Content.FRUIT_SALAD);
        provider.basicItem(Content.VEGGIE_SALAD);
        provider.basicItem(Content.PORK_AND_BEANS);
        provider.basicItem(Content.OATMEAL);
        provider.basicItem(Content.LEEK_SOUP);
        provider.basicItem(Content.YOGHURT);
        provider.basicItem(Content.SAUCY_CHIPS);
        provider.basicItem(Content.ROASTED_NUTS);
        provider.basicItem(Content.TRAIL_MIX);
        provider.basicItem(Content.PROTEIN_BAR);
        provider.basicItem(Content.NOUGAT);
        provider.basicItem(Content.SCRAMBLED_EGGS);
        provider.basicItem(Content.BUTTERED_TOAST);
        provider.basicItem(Content.TOAST_WITH_JAM);
        provider.basicItem(Content.HAM_SANDWICH);
        provider.basicItem(Content.PEANUT_BUTTER_AND_JAM);
        provider.basicItem(Content.BLT);
        provider.basicItem(Content.GRILLED_CHEESE);
        provider.basicItem(Content.TUNA_SANDWICH);
        provider.basicItem(Content.CHEESEBURGER);
        provider.basicItem(Content.HAMBURGER);
        provider.basicItem(Content.TOFUBURGER);
        provider.basicItem(Content.PIZZA);
        provider.basicItem(Content.SUPREME_PIZZA);
        provider.basicItem(Content.CHEESE_PIZZA);
        provider.basicItem(Content.PINEAPPLE_PEPPERONI_PIZZA);
        provider.basicItem(Content.LEMON_CHICKEN);
        provider.basicItem(Content.FRIED_CHICKEN);
        provider.basicItem(Content.CHICKEN_AND_NOODLES);
        provider.basicItem(Content.CHICKEN_AND_DUMPLINGS);
        provider.basicItem(Content.TOFU_AND_DUMPLINGS);
        provider.basicItem(Content.SPAGHETTI_SQUASH);
        provider.basicItem(Content.CHICKEN_AND_RICE);
        provider.basicItem(Content.TACO);
        provider.basicItem(Content.SUSHI);
        provider.basicItem(Content.EGG_ROLL);
        provider.basicItem(Content.CASHEW_CHICKEN);
        provider.basicItem(Content.YAM_JAM);
        provider.basicItem(Content.BANANA_CREAM_PIE);
        provider.basicItem(Content.CANDY_CORN);
        provider.basicItem(Content.RUM_RAISIN_ICE_CREAM);
        provider.basicItem(Content.CHEESE_CAKE);
        provider.basicItem(Content.BROWNIES);
        provider.basicItem(Content.SNICKER_DOODLE);
        provider.basicItem(Content.BANANA_NUT_BREAD);
        provider.basicItem(Content.CANDIED_NUTS);
        provider.basicItem(Content.ALMOND_BRITTLE);
        provider.basicItem(Content.OATMEAL_COOKIE);
        provider.basicItem(Content.NUTTY_COOKIE);
        provider.basicItem(Content.BURRITO);
        provider.basicItem(Content.TOSTADA);
        provider.basicItem(Content.HORCHATA);
        provider.basicItem(Content.CARNITAS);
        provider.basicItem(Content.FAJITAS);
        provider.basicItem(Content.ENCHILADA);
        provider.basicItem(Content.CHURROS);
        provider.basicItem(Content.TAMALES);
        provider.basicItem(Content.TRES_LECHE_CAKE);
        provider.basicItem(Content.STUFFED_POBLANOS);
        provider.basicItem(Content.CHILI_RELLENO);
        provider.basicItem(Content.CREMA);
        provider.basicItem(Content.REFRIED_BEANS);
        provider.basicItem(Content.CHIMICHANGA);
        provider.basicItem(Content.QUESADILLA);
        provider.basicItem(Content.CORN_HUSK);
        provider.basicItem(Content.WHIPPING_CREAM);
        provider.basicItem(Content.SHEPHERDS_PIE);
        provider.basicItem(Content.BEEF_WELLINGTON);
        provider.basicItem(Content.FISH_AND_CHIPS);
        provider.basicItem(Content.ETON_MESS);
        provider.basicItem(Content.TEA);
        provider.basicItem(Content.CORNISH_PASTY);
        provider.basicItem(Content.SCONES);
        provider.basicItem(Content.FIGGY_PUDDING);
        provider.basicItem(Content.TREACLE_TART);
        provider.basicItem(Content.STICKY_TOFFEE_PUDDING);
        provider.basicItem(Content.TRIFLE);
        provider.basicItem(Content.WATER_BOTTLE);
        provider.basicItem(Content.MILK_BOTTLE);
        provider.basicItem(Content.AJVAR);
        provider.basicItem(Content.AJVAR_TOAST);
        provider.basicItem(Content.AVOCADO_TOAST);
        provider.basicItem(Content.BEEF_STEW);
        provider.basicItem(Content.BEEF_STIR_FRY);
        provider.basicItem(Content.BUTTERED_GREEN_BEANS);
        provider.basicItem(Content.CHEESY_ASPARAGUS);
        provider.basicItem(Content.CHOCOLATE_ICE_CREAM);
        provider.basicItem(Content.EGGPLANT_PARMESAN);
        provider.basicItem(Content.FRUIT_CAKE);
        provider.basicItem(Content.GRILLED_EGGPLANT);
        provider.basicItem(Content.KIWI_SORBET);
        provider.basicItem(Content.LEMON_COCONUT_BAR);
        provider.basicItem(Content.NETHER_WART_STEW);
        provider.basicItem(Content.PEANUT_BUTTER);
        provider.basicItem(Content.PEANUT_BUTTER_W_CELERY);
        provider.basicItem(Content.POTATO_SOUP);
        provider.basicItem(Content.RATATOUILLE);
        provider.basicItem(Content.RAW_BACON);
        provider.basicItem(Content.RHUBARB_CRISP);
        provider.basicItem(Content.ROASTED_ASPARAGUS);
        provider.basicItem(Content.ROASTED_RADISHES);
        provider.basicItem(Content.ROASTED_SQUASH);
        provider.basicItem(Content.ROASTED_TURNIPS);
        provider.basicItem(Content.STEAMED_BROCCOLI);
        provider.basicItem(Content.STEAMED_GREEN_BEANS);
        provider.basicItem(Content.STIR_FRY);
        provider.basicItem(Content.STUFFED_ARTICHOKE);
        provider.basicItem(Content.TOAST_SANDWICH);
        provider.basicItem(Content.ROASTED_PUMPKIN_SEEDS);
        provider.basicItem(Content.ROASTED_SUNFLOWER_SEEDS);
        provider.basicItem(Content.PUMPKIN_BARS);
        provider.basicItem(Content.CORN_BREAD);
        provider.basicItem(Content.PUMPKIN_SOUP);
        provider.basicItem(Content.MERINGUE);
        provider.basicItem(Content.CABBAGE_ROLL);
        provider.basicItem(Content.BORSCHT);
        provider.basicItem(Content.GOULASH);
        provider.basicItem(Content.BEETROOT_SALAD);
        provider.basicItem(Content.CANDIED_KUMQUATS);
        provider.basicItem(Content.SHRIMP.asItem());
        provider.basicItem(Content.TUNA.asItem());
        provider.basicItem(Content.CALAMARI.asItem());
        provider.basicItem(Content.CRAB.asItem());
        provider.basicItem(Content.ROE.asItem());
        provider.basicItem(Content.CLAM.asItem());
        provider.basicItem(Content.OYSTER.asItem());
        provider.basicItem(Content.COOKED_SHRIMP.asItem());
        provider.basicItem(Content.COOKED_TUNA.asItem());
        provider.basicItem(Content.COOKED_CALAMARI.asItem());
        provider.basicItem(Content.STEAMED_CRAB);
        provider.basicItem(Content.GLOWING_CALAMARI.asItem());
        provider.basicItem(Content.SEA_LETTUCE);
        provider.basicItem(Content.DEEP_FRIED_SHRIMP);
        provider.basicItem(Content.TUNA_ROLL);
        provider.basicItem(Content.FRIED_CALAMARI);
        provider.basicItem(Content.CRAB_LEGS);
        provider.basicItem(Content.STEAMED_CLAMS);
        provider.basicItem(Content.GRILLED_OYSTERS);
        provider.basicItem(Content.ANCHOVY.asItem());
        provider.basicItem(Content.COOKED_ANCHOVY.asItem());
        provider.basicItem(Content.ANCHOVY_PIZZA);
        provider.basicItem(Content.MASHED_POTATOES);
        provider.basicItem(Content.BAKED_CREPES);
        provider.basicItem(Content.CINNAMON_ROLL);
        provider.basicItem(Content.CROQUE_MADAME);
        provider.basicItem(Content.CROQUE_MONSIEUR);
        provider.basicItem(Content.DAUPHINE_POTATOES);
        provider.basicItem(Content.FRIED_FROG_LEGS);
        provider.basicItem(Content.FROG_LEGS);
        provider.basicItem(Content.GROUND_PORK);
        provider.basicItem(Content.HASHED_BROWN);
        provider.basicItem(Content.MACARON);
        provider.basicItem(Content.QUICHE);
        provider.basicItem(Content.SAUSAGE);
        provider.basicItem(Content.SUNNY_SIDE_EGGS);
        provider.basicItem(Content.SWEET_CREPES);
        provider.basicItem(Content.THE_BIG_BREAKFAST);

        provider.basicItem(Content.COOKED_RAVAGER_MEAT.asItem());
        provider.basicItem(Content.DRAGON_EGG_OMELETTE);
        provider.basicItem(Content.MOUNTAIN_SALT);
        provider.basicItem(Content.NETHER_STAR_CAKE);
        provider.basicItem(Content.RAW_RAVAGER_MEAT);
        provider.basicItem(Content.TRANSCENDENTAL_BREAKFAST);

        simpleBlockStage1Item(provider, Content.ALMOND.asBlock());
        simpleBlockStage1Item(provider, Content.APPLE.asBlock());
        simpleBlockStage1Item(provider, Content.APRICOT.asBlock());
        simpleBlockStage1Item(provider, Content.AVOCADO.asBlock());
        simpleBlockStage1Item(provider, Content.BANANA.asBlock());
        simpleBlockStage1Item(provider, Content.CASHEW.asBlock());
        simpleBlockStage1Item(provider, Content.CHERRY.asBlock());
        simpleBlockStage1Item(provider, Content.COCONUT.asBlock());
        simpleBlockStage1Item(provider, Content.DATE.asBlock());
        simpleBlockStage1Item(provider, Content.DRAGONFRUIT.asBlock());
        simpleBlockStage1Item(provider, Content.FIG.asBlock());
        simpleBlockStage1Item(provider, Content.GRAPEFRUIT.asBlock());
        simpleBlockStage1Item(provider, Content.KUMQUAT.asBlock());
        simpleBlockStage1Item(provider, Content.LEMON.asBlock());
        simpleBlockStage1Item(provider, Content.LIME.asBlock());
        simpleBlockStage1Item(provider, Content.MANGO.asBlock());
        simpleBlockStage1Item(provider, Content.NECTARINE.asBlock());
        simpleBlockStage1Item(provider, Content.NUTMEG.asBlock());
        simpleBlockStage1Item(provider, Content.ORANGE.asBlock());
        simpleBlockStage1Item(provider, Content.PEACH.asBlock());
        simpleBlockStage1Item(provider, Content.PEAR.asBlock());
        simpleBlockStage1Item(provider, Content.PECAN.asBlock());
        simpleBlockStage1Item(provider, Content.PERSIMMON.asBlock());
        simpleBlockStage1Item(provider, Content.PLUM.asBlock());
        simpleBlockStage1Item(provider, Content.STARFRUIT.asBlock());
        simpleBlockStage1Item(provider, Content.WALNUT.asBlock());
    }

    protected void simpleBlockStage1Item(ItemModelProvider provider, Block block) {
        ResourceLocation id = BuiltInRegistries.BLOCK.getKey(block);
        if (id == null) {
            throw new IllegalStateException("Unregistered block passed to simpleBlockStage1Item: " + block);
        }

        // item model file name is the block’s path; parent points to block/<path>_stage1
        provider.withExistingParent(id.getPath(),
                modLoc(ModelProvider.BLOCK_FOLDER + "/" + id.getPath() + "_stage1"));
    }


    @Override
    protected void registerStatesAndModels() {
        registerItemModels(itemModels());
    }

}
